server:
  port: 9509
  
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICES
          uri: lb://USER-SERVICES
          predicates:
            - Path=/MicroService2/user/**
          filters:
            - name: CircuitBreaker
              args:
                name: USER-SERVICES
                fallbackuri: forward:/userServiceFallBack
        - id: DEPARTMENT-SERVICES
          uri: lb://DEPARTMENT-SERVICES
          predicates:
            - Path=/MicroService1/department/**
          filters:
            - name: CircuitBreaker
              args:
                name: DEPARTMENT-SERVICES
                fallbackuri: forward:/departmentServiceFallBack
                
hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

        
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#    fetch-registry: true
#    register-with-eureka: true
#  instance:
#    hostname: localhost

