#server.port=9501
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto=update
#spring.datasource.url=jdbc:postgresql://localhost:5432/VishalDB
#spring.datasource.username=postgres
#spring.datasource.password=Vishal@91289
##spring.datasource.driver-class-name=com.postgresql.Driver
#spring.jpa.show-sql: true
#server.servlet.context-path=/MicroService1
#
#eureka.client.register-with-eureka=true
#eureka.client.fetch-registry=true
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka
#eureka.instance.hostname=localhost
#
#spring.application.name=DEPARTMENT-SERVICES


server:
  port: 9501
  servlet:
    context-path: /MicroService1

spring:
  application:
    name: DEPARTMENT-SERVICES
  zipkin:
    base-url: http://127.0.0.1:9411/
  datasource:
    url: jdbc:postgresql://localhost:5432/VishalDB
    username: postgres
    password: Vishal@91289

    
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#    fetch-registry: true
#    register-with-eureka: true
#  instance:
#    hostname: localhost

  